version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: images-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    restart: always
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge